### ISSUE TITLE
Playlist link of event pages

### ISSUE THREAD

**Issue by rikkilake** [mdjmplugin/mobile-dj-manager#100]
If I apply a filter, e.g. Confirmed, the value of an associated play list shows zero songs added. If I apply no filters and page through to the event it shows a positive value, which when clicked returns the play list - with certainly more than zero songs.

Nearly got caught out by this this weekend when a customer said they had requested 30 songs, but the link text said zero.

**Comment by rikkilake** [comment]
It still shows zero songs.
Look up 25 Jun 2016 - Lorna Coates - Awaiting Contract, try with filter and without filter.

**Comment by mikeyhoward1977** [comment]
I haven’t pushed the update yet!

**Comment by rikkilake** [comment]
Oh right haha.. I just saw an update in Plug-ins and went with that! Guess you've been doing a lot of commits recently!
