### ISSUE TITLE
Change wording in transactions

### ISSUE THREAD

**Issue by peter8rossi** [mdjmplugin/mobile-dj-manager#103]
Could we change the word "Completed" to perhaps "Paid" in the status selection on transactions. I got a momentary scare when I went to the transaction and saw "Status" as " Completed" for an event that was only "Confirmed" - got the Event Status confused with the Payment Status. The simple word change would up prevent anyone else from being similarly confused.

**Comment by mikeyhoward1977** [comment]
This would involve many changes to core code as well as add-ons, not to mention a significant upgrade process to address all existing transactions.

We've never had any concern over the term previously and therefore I would not consider such a change at this time.
