### ISSUE TITLE
Wrong due in CZK

### ISSUE THREAD

**Issue by petrknap1** [mdjmplugin/mobile-dj-manager#105]
Hello,

after update to 1.3.7.6., I have problem in due value.
Total price is 6000 CZK, Transaction is also 6000 CZK. Summary is wrong.

Thank you

![due](https://cloud.githubusercontent.com/assets/19391308/16432564/d054e5d6-3d85-11e6-9447-40b5ea1bab21.jpg)

**Comment by mydjplanner** [comment]
Have any payments been registered against this event?

From: petrknap1 
Sent: Tuesday, June 28, 2016 10:15 PM
To: mdjm/mobile-dj-manager 
Subject: [mdjm/mobile-dj-manager] Wrong due in CZK (#105)

Hello,

after update to 1.3.7.6., I have problem in due value.
Total price is 6000 CZK, Transaction is also 6000 CZK. Summary is wrong.

Thank you

**Comment by mikeyhoward1977** [comment]
@petrknap1 This issue should now be resolved with version 1.3.7.7. You may find that some of your due amounts show incorrectly on the event list page. If they do, simply open the event and save without making any changes. That should resolve
