### ISSUE TITLE
Payment Emails are sent when "Disable Client Email" is selected

### ISSUE THREAD

**Issue by peter8rossi** [mdjmplugin/mobile-dj-manager#110]
With "Disable Client Emails" selected on the event screen, ticking the "Balance" or "Deposit" paid check boxes still generates the payment email as set under email template settings.

**Comment by mikeyhoward1977** [comment]
That is correct. Payment emails are defined under Email template settings. See the option, Manual Payment Template. Set this to None if you do not want emails sent with manual payments.

"Disable Client Emails" refers to event status change emails, not payments

**Comment by peter8rossi** [comment]
It should be made clearer that "Disable Client Emails" refers to event status change emails, not payments, perhaps by stating "Disable Status Change Emails". With the Payment emails template selection being grouped in with the other status change emails, in Email Templates Settings, it is easy to see why the "Disable Client Emails" would be thought to apply to payment emails as well.

I usually want to send the payment email, but on occasions I want to override this and not send the payment received email. Do I have to go and change the settings, sent the email and then reset the setting?

**Comment by mikeyhoward1977** [comment]
It's been like that since forever.

If you want to disable on a per transaction basis you can un-select the checkbox within the add transaction section of the event screen and add the transaction there. Add an amount that is equal to, or exceeds the deposit/balance will mark them as paid
