### ISSUE TITLE
Google Calendar - Shortcodes not working

### ISSUE THREAD

**Issue by rikkilake** [mdjmplugin/mobile-dj-manager#119]
Hello,

I've pinned this on-going Google Calendar issue to 2 specific shortcodes.

{deposit} and {balance}

If I use either of these shortcodes in Entry Title or Content fields it completely invalidates the field returning a zero string.

**Comment by mikeyhoward1977** [comment]
Hi @rikkilake,

I cannot replicate this. I can also confirm that for other users they are able to use these shortcodes and have no issue with the calendar updating.

Your WordPress debug file is infected with so many entries it is quite difficult to interpret however I have confirmed there are no entries containing "mobile" or "mdjm".

A few things to try...
1. Go to MDJM -> Settings -> Payments. Make sure you have a currency etc. set and Save Changes.
   Try editing and saving an event - see if it works.
2. Can you enable MDJM debugging and then save an active event (active meaning one that the calendar is set to sync).
3. Then repeat the save for another event (active again) but this time with all your other plugins deactivated.

If you could let me know once these steps are completed with a rough time that you attempted that would be a great help

Thanks
Mike

**Comment by rikkilake** [comment]
Hello,

Well no luck with Step 1 or disabling all other plug-ins.

As requested:

Step 2: 15:26 - BOOG3578

Step 3: 15:30 - BOOG3574

Curious to know what other debugging is taking place on the website besides
MDJM...

**Comment by mikeyhoward1977** [comment]
@rikkilake 

> Curious to know what other debugging is taking place on the website besides MDJM

You have WP debugging enabled in your wp-config.php file. Logs are being written every few seconds. It doesn't appear that any are critical so I doubt fixing those would resolve any problems you have, but it won't help with web performance.

https://codex.wordpress.org/Debugging_in_WordPress

**Comment by mikeyhoward1977** [comment]
@rikkilake 

Thanks for enabling MDJM debugging.

When we send a request to Google we wait for the response before logging by catching exceptions. If an exception is received (request fail) we print that exception to the MDJM log file - There are no such entries in your file.

Likewise, if Google confirms the request was received and processed successfully, we print to the log file "GCal Calendar entry for <event_id> successfully created/updated". We then print the entire communication that Google received. Your log file has these entries indicating the request was successful.

Snippet from your log file...

>  Updating existing calendar entry
>     GCal Calendar entry *******_cf1sahp**_*\* successfully updated for event 3578
>     Google_Service_Calendar_Event::__set_state(array(
>    'collection_key' => 'recurrence',
>    'internal_gapi_mappings' => 
>   array (
>   ),
>    'anyoneCanAddSelf' => NULL,
>    'attachmentsType' => 'Google_Service_Calendar_EventAttachment',
>    'attachmentsDataType' => 'array',
>    'attendeesType' => 'Google_Service_Calendar_EventAttendee',
>    'attendeesDataType' => 'array',
>    'attendeesOmitted' => NULL,
>    'colorId' => NULL,
>    'created' => '2016-06-26T22:00:58.000Z',
>    'creatorType' => 'Google_Service_Calendar_EventCreator',
>    'creatorDataType' => '',
>    'description' => 'Setup: 19:00
> Event ID: BOOG3578 / Other 
> Event Notes: Karaoke night
> DJ: *******
> Amount to Collect: £85.00
> Deposit Requested: £0.00 (Paid)
> DJ Notes: ',

There is much more data in there but all seems to be as expected. I've also replicated the title, venue and content you have within the calendar settings on my install and all works as expected

One important thing I did notice is that you are running a very old and unsupported version of PHP on your webserver - 5.3. I would recommend updating to a supported version as soon as possible. You should be able to do this via your web hosts control panel, if not you will need to contact them.

We do run code that is not compatible with 5.3. I can't think of anything that would impact the calendar plugin off the top of my head but it is worth trying again post update

**Comment by rikkilake** [comment]
Hi Mike,

SOLVED

You were correct about PHP 5.3 being possibly an issue.

I have a dedicated server with Heart Internet so I have installed 5.6.23 and
enabled it on that domain.

All is well, I have manually updated 2 events and both of them contain the
'description' field as intended. =)

Now I have to manually update each and every event in order for it show... but
at least it'll be done from now on.  Thank you for all your help.

Richard

**Comment by mikeyhoward1977** [comment]
Awesome :) We got there in the end...

No need to manually update each event. Just ensure daily sync is enabled and within 24 hours all will be well. Or to make it happen sooner, deactivate the calendar plugin. Re-activate and ensure daily sync is active - it will run after 1 hour and then every 24 hours thereafter
