### ISSUE TITLE
Shortcodes bug in email templates

### ISSUE THREAD

**Issue by petrknap1** [mdjmplugin/mobile-dj-manager#121]
Hello,

{CLIENT_FULLNAME} - show DJ fullname
{DJ_EMAIL} - show nothing

Thank you.
![shortcode bug](https://cloud.githubusercontent.com/assets/19391308/16985043/300c68e2-4e7e-11e6-8235-70b474e75516.jpg)

**Comment by mikeyhoward1977** [comment]
Hi @petrknap1,

That is very odd. Can you send me an admin login with full MDJM rights to support [at] mdjm.co.uk and I will take a look.

Also, during what process was this template sent? and which event ID is it referring to?

Thanks
Mike

**Comment by petrknap1** [comment]
The teplate is send after sign a contract, change status from Awaiting Contract -> Confirmed by all events.

**Comment by mikeyhoward1977** [comment]
@petrknap1 - I need to to take a look to be sure of what is going on

**Comment by mikeyhoward1977** [comment]
@petrknap1 I found my account - username MDJM - You need to edit the profile and make me an MDJM Admin please

**Comment by petrknap1** [comment]
Try it, thank you

**Comment by mikeyhoward1977** [comment]
@petrknap1 What version of PHP is your website running?

**Comment by petrknap1** [comment]
@mikeyhoward1977 The version of My PHP Admin is "3.4.10.1deb1".

**Comment by mydjplanner** [comment]
Can you verify as that does not appear correct. I need the version of PHP that your web server has installed 

On 20 Jul 2016, at 15:05, petrknap1 notifications@github.com wrote:

@mikeyhoward1977 The version is "3.4.10.1deb1".

**Comment by petrknap1** [comment]
PHP 5.4.
