### ISSUE TITLE
Review (sent) Email page

### ISSUE THREAD

**Issue by rikkilake** [mdjmplugin/mobile-dj-manager#125]
Hello,

Hover your mouse over the recipient url in the Details box to the right of the screen reveals the resource name within the mysql_fetch_object command rather than the actual userid - thus when clicked the message Invalid user ID is displayed in the error box.

**Comment by mikeyhoward1977** [comment]
Hi @rikkilake,

Which screen?

**Comment by rikkilake** [comment]
Go to Email History, click on the Email Subject title within a row to open Review Email page.

**Comment by mikeyhoward1977** [comment]
@rikkilake - Thanks, I have resolved and will push an update later today
