### ISSUE TITLE
Set Default Report Period

### ISSUE THREAD

**Issue by rikkilake** [mdjmplugin/mobile-dj-manager#140]
Thanks for the new Reporting ability.

Hopefully the title says it all, at present the reporting period defaults to 'This Month'.  Whenever I choose another Report it keeps reverting back.  It would be useful to set this or otherwise it gets saved in the URL parameters as a user navigates through the Report types.

**Comment by mikeyhoward1977** [comment]
Hi @rikkilake,

Thanks for the suggestion. I won't look to change this currently as they are two separate forms to each other and a quick review suggests quite a bit of work to adjust which, given it is quite minor, I do not have time for right now.

If you are able to take a look I would love a pull request :)

**Comment by rikkilake** [comment]
Hi Mike,

I trust you spotted my facebook comment concerning the Google Calendar add-on
issue in 1.4?

The shortcodes for both client forename and surname have disappeared from the
output of newly added events.

All other fields and shortcodes are working.

Event Title = ({event_status}) {client_firstname} {client_lastname} -
{event_type}

Richard

**Comment by mikeyhoward1977** [comment]
Hi @rikkilake 

Please update to 1.4.1 (released a short while ago) and re-try. I have just tested on 3 installs using the exact content tags you provided above and each time it worked ok.

If you are still having an issue, please copy and paste the data from the MDJM -> Tools -> System Info tab into an email to me

**Comment by rikkilake** [comment]
Hello,

Updated main plug-in, same behaviour, I tried toggling both plug-ins on and off,
still same behaviour upon saving events.

Please find attached system info file.

PS. Thanks 1.4.1, I wondered why the Dashboard won't load correctly this
morning.

Richard

**Comment by mikeyhoward1977** [comment]
Could you enable MDJM Debugging, and also if possible WP debugging?

I will then review those logs after a short period

**Comment by mikeyhoward1977** [comment]
@rikkilake thanks for enabling debugging. Would you also be able to make my WP account an Administrator temporarily?

**Comment by rikkilake** [comment]
Done.

**Comment by mikeyhoward1977** [comment]
You can disable debugging - thanks. I'll come back shortly once I've run some tests

**Comment by mikeyhoward1977** [comment]
Hi @rikkilake,

Sorry for the delay... Since you are using `{client_firstname}` and `{client_surname}` you need to ensure that the WP user profile has these fields populated for the client.

What I am seeing for event ID 4237 is that the client has a nickname and a display name set in their WP profile, but no first or last name which is where those two content tags are pulling from.

If you do not wish to populate these fields, as an alternative, use `{client_fullname}`. That content tag pulls from the display name field from the user profile.

**Comment by rikkilake** [comment]
Hi Mike,

Brilliant, thanks for pinpointing the issue.  I am more than happy to use
{client_fullname} - which works.

Richard

**Comment by mikeyhoward1977** [comment]
@rikkilake Looking further at this there seems to be a bug associated which effects users created via the event screen.

I have opened Issue #148. Will address and push an update later today
