### ISSUE TITLE
No Login on Client Zone - Urgent

### ISSUE THREAD

**Issue by peter8rossi** [mdjmplugin/mobile-dj-manager#15]
If you are not logged in and go to the Client Zone, you are met with a blank screen. There no longer is a dialog box to log in. Using http://siteurl/wp-login.php? you can access the login screen an there after the client, typical Client Zone page displays.

**Comment by mikeyhoward1977** [comment]
Hi Peter - this seems to be limited to your site. Please provide me with a login and I'll take a look for you. I think I have an existing account, just make that an Admin in WP and then edit the user and check the MDJM Admin checkbox.

**Comment by peter8rossi** [comment]
Theme related issue

**Comment by mikeyhoward1977** [comment]
Per user note, this is a theme related issue
