### ISSUE TITLE
Apostrophes in Contact Form name

### ISSUE THREAD

**Issue by rikkilake** [mdjmplugin/mobile-dj-manager#156]
Hello,

Single apostrophes in Contact Form names aren't handled very well... e.g. Childrens' parties

**Comment by mydjplanner** [comment]
This is not the issue log for contact forms. It is for core MDJM only.

Closing... log via mdjm.co.uk or email directly to the support address

On 26 Sep 2016, at 19:10, rikkilake notifications@github.com wrote:

Hello,

Single apostrophes in Contact Form names aren't handled very well... e.g. Childrens' parties

**Comment by rikkilake** [comment]
Where do i report these?
