### ISSUE TITLE
Contract Signature Page layout broken

### ISSUE THREAD

**Issue by nikmartin** [mdjmplugin/mobile-dj-manager#162]
I'm using the Spacious theme, which is supposedly mobile responsive, but the contract signature pge ends up looking like:
![screenshot from 2016-09-28 00-38-05](https://cloud.githubusercontent.com/assets/1226452/18902047/96918b4c-8515-11e6-80a3-5cb887d53723.png)

**Comment by mikeyhoward1977** [comment]
Have you adjusted any CSS in relation to this page or the template itself? Testing on my own sites everything is lined up and sizes are auto adjusted when the page is resized.

You could try editing the templates/mdjm.css file and for the following two sections adjust the width down by a couple of percent... 47% should do it

``` javascript
/* =Contracts Page
-------------------------------------------------------------- */
#mdjm-contract-signature-form .col  {
    padding-right: 5px;
    float: left;
    width: 50%;
}

#mdjm-contract-signature-form .last {
    padding-left: 5px;
    float: right;
    width: 50%;
}
```

Let me know
