### ISSUE TITLE
Dynamic Contact Forms - Error, securify verication failed

### ISSUE THREAD

**Issue by rikkilake** [mdjmplugin/mobile-dj-manager#173]
Hi Mike,

"Error, security verification failed."

Customers keep reporting that when they complete a contact form and click Submit the contact form empties and shows this error message at the top of the form.  I've seen this also myself - of course this could be losing me business without me knowing about it - it has been reported at least twice already over the phone.  Please find a little time to debug, thank you.

**Comment by mikeyhoward1977** [comment]
Hi,

This is in relation to the Dynamic Contact Forms plugin. This repo is for the core plugin only.

I'll close the comment and create a support ticket at https://mdjm.co.uk which is where this should be submitted.
