### ISSUE TITLE
Failed/Rejected Enquiries and the Client status

### ISSUE THREAD

**Issue by rikkilake** [mdjmplugin/mobile-dj-manager#183]
Today when I set BOOG7517 to Failed Enquiry the client was set to Inactive Client - which I don't feel shouldn't happen, the administrator should set this themselves, a repeat client might Fail an Enquiry and accept the next - anyway this wasn't why I came here today.

When I clicked on Update Event, if you look at the Client Details metabox; the drop-down menu is now empty.  The drop-down menu shouldn't be excluding Inactive Clients.  (I have since manually found the User and made him Active again - and re-updated the event - this is the only way to visually get that drop-down menu populated).

I have also noticed that Inactive Clients appear as 'Recipient no longer exists' in the Email History - have they died?

Also in the admin area of Email History my From column has read 'Array' for as long as care to remember.

**Comment by mikeyhoward1977** [comment]
Go to MDJM Settings -> Events...

![inactive-client-setting](https://user-images.githubusercontent.com/11500622/27883066-2872218c-61c7-11e7-9ae4-43c944d750d4.jpg)

**Comment by rikkilake** [comment]
Doh, feel like such a wally. Thank you.

**Comment by mikeyhoward1977** [comment]
NP - I will create separate tickets for the other items you mentioned - easier to track with single topic tickets :)
