### ISSUE TITLE
Disabled Visual Editor and Communications screen

### ISSUE THREAD

**Issue by rikkilake** [mdjmplugin/mobile-dj-manager#195]
In my Profile if I tick the global setting 'Disable the visual editor when writing' (my preferred way of working with the new site) and go the Communications screen, select a Client and an Event and finally a Template; the Text editor refuses to "Load" the html of the selected Template into the textarea.

**Comment by deckbooks** [comment]
HI @rikkilake thank you for reporting this issue, we have reproduced this and will fix this in our next release
