### ISSUE TITLE
login-form.php 

### ISSUE THREAD

**Issue by lunaed** [mdjmplugin/mobile-dj-manager#199]
Fabulous plugin, just letting you know that on the page with the [mdjm-home] shortcode, my footer has been swallowed by a wayward div...

/plugins/mobile-dj-manager/templates/login/login-form.php 

Final line is currently hanging: <!-- endif( ! user_is_logged_in() ) )

Best,
Hannah

**Comment by mikeyhoward1977** [comment]
Close comment tag is missing from login-form.php template

**Comment by lunaed** [comment]
Thanks, just letting you know!
