### ISSUE TITLE
Contact form

### ISSUE THREAD

**Issue by IggyDavis** [mdjmplugin/mobile-dj-manager#207]
I sent an email yesterday regarding my contact form which appears after the availability checker not working after an update. (availability checker is at the footer of every page btw)
I believe there is a conflict with the theme. 
www.iggyweddingdj.com

**Comment by mikeyhoward1977** [comment]
Iggy - Please log a support ticket via our website and I'll be happy to help. GitHub issues are for code bugs and enhancement requests.

Thanks
Mike
