### ISSUE TITLE
Defer contract signing until deposit is received

### ISSUE THREAD

**Issue by mikeyhoward1977** [mdjmplugin/mobile-dj-manager#211]
We should have an option to withhold the signing of a contract by a client if they have not paid the required deposit.

A setting should exist to allow admins to enforce this policy or not. Turned off by default.

Core MDJM should simply disable the fields for signing the contract and display a notice on the contract signing page.

The Payment gateway add-ons (PayPal, PayFast and Stripe) should provide the option to make the payment as part of the contract signing process.

**Comment by peter8rossi** [comment]
The client should not be withheld from signing the contract, but rather the contract does not become a confirmed booking until payment is received. Typically a contract is where the up front payment requirement is stated (as demonstrated in the MDJM default contract), so signing after receiving payment is not how the work flow goes.

Signing the contract should then provide payment options to the client, of which a Payment Gateway could be one.
