### ISSUE TITLE
Licence expiration dates not updating

### ISSUE THREAD

**Issue by peter8rossi** [mdjmplugin/mobile-dj-manager#220]
The expiration dates for my Calendar Sync and Contact Form are not updating in settings:
![capture-settings](https://user-images.githubusercontent.com/19335843/40663135-0a330d74-6326-11e8-8ba7-ff0099d313a0.JPG)
![capture-account-page](https://user-images.githubusercontent.com/19335843/40663156-10705bf6-6326-11e8-864d-deb9d6c6935c.JPG)

**Comment by mikeyhoward1977** [comment]
@peter8rossi - Use the normal support channel for these types of issues please - https://mdjm.co.uk/support.

In this instance, try deactivating and reactivating your licenses
