### ISSUE TITLE
The event_name field not showing on the event page V1.5

### ISSUE THREAD

**Issue by peter8rossi** [mdjmplugin/mobile-dj-manager#221]
The event_name field is not showing on the create or edit event page. It still shows on the event list page, but there is no place to enter this information. The name of an event is key detail and should be on the screen. It is referenced in all my client emails and without this field I can not use MDJM.

**Comment by mikeyhoward1977** [comment]
hi @peter8rossi The event name field is now the title field - i.e. the same field you use to enter the title of a page or post
