### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by waynehaffenden** [mdjmplugin/mobile-dj-manager#235]
Fully support PHP 8 with this plugin ready for when WordPress does.

**Comment by deckbooks** [comment]
Hi @waynehaffenden we'll be very close to start looking at supporting PHP 8.0 soon

**Comment by mdjmplugin** [comment]
Hi @waynehaffenden I've done some initial test with the 1.5.9-rc.1 pre-release and it looks like it works pretty well on PHP 8

**Comment by jackjpdiscos** [comment]
MDJM is now compatible with PHP 8
