### ISSUE TITLE
Plug-in extension - google calender

### ISSUE THREAD

**Issue by nowentertainme** [mdjmplugin/mobile-dj-manager#238]
Hi, I installed the new free extension (Thankyou) I have managed to link the calendar with plug-in, however it does not seem to be syncing and no events are showing?

**Comment by deckbooks** [comment]
Hi, under Settings->Extensions->Google Calendar have you selected the event status you wish to sync to Google Calendar under the option "Sync Events with Status"

**Comment by nowentertainme** [comment]
Hi, yes I have done that ![image](https://user-images.githubusercontent.com/79471613/111038205-a9a5cc80-841f-11eb-9abf-8f53c009e045.jpeg)

**Comment by deckbooks** [comment]
Thank you could you send a full screenshot of that page to the support team at support@mdjm.co.uk

**Comment by jackjpdiscos** [comment]
Hi, did you get this sorted?
