### ISSUE TITLE
The contract could not be displayed

### ISSUE THREAD

**Issue by petrknap1** [mdjmplugin/mobile-dj-manager#45]
Hello one again,

if I want to sign contract in client zone, the contract doesn't show me and when I want to sign it, display me error message: Error: Unable to sign event contract.

Thank you.
Petr

**Comment by mikeyhoward1977** [comment]
Hi,

That error is only displayed in 3 circumstances...
1. An event ID cannot be obtained
2. No contract template exists
3. WordPress is unable to insert the new signed contract post

Your MDJM debug log shows no errors. Can you install the **Debug** plugin. Once activated from the left menu, go to Debug -> Settings and enable all but the first and fourth settings. Then try again and let me know when done.

![image](https://cloud.githubusercontent.com/assets/11500622/15354058/b80bccd2-1ce3-11e6-8821-4a50fc9b8246.png)

**Comment by petrknap1** [comment]
It's the same: "The contract could not be displayed"

I have contract templates. It was good before update to MDJM 1.3.

**Comment by mikeyhoward1977** [comment]
What version are you running now?

Can you send me the URL you are using to access the contract? Do you see the contract at all?

Can you also confirm that you are logging into the client zone as the client and not as admin

**Comment by petrknap1** [comment]
Link to sign contract: http://www.kv-production.cz/client-zone/client-contracts/?event_id=1180
Login: jan.drn86@seznam.cz
Pass: jan.drn86@seznam.cz

If I open older events, I see the contracts. If I create new event now, I don't see the contract.

**Comment by mikeyhoward1977** [comment]
could you create me an admin account and send to me? use support AT mydjplanner.co.uk for the email

**Comment by mikeyhoward1977** [comment]
I have tried to replicate this issue on 3 different sites. 2 x existing installs at various MDJM levels and a brand new install. I cannot replicate the issue. With new or old events.

The error "The contract could not be displayed" is only generated if the contract cannot be found (WordPress) post.

Therefore, please ensure that...
1. You have a contract template under MDJM -> Contract Templates
2. This contract is assigned as the default event contract in MDJM -> Settings -> Events
3. The event with ID 1180 has this contract assigned as the event contract

I cannot debug any further without admin access I'm afraid so I await your response, but at this stage it does not appear to be any type of bug.

**Comment by petrknap1** [comment]
I think it's no. 3.

I created you an admin account.

![contract](https://cloud.githubusercontent.com/assets/19391308/15373037/d0c8da84-1d43-11e6-9b3a-1400a5495036.jpg)

**Comment by mikeyhoward1977** [comment]
Under my user account, please enable the following under the MDJM Event Management section, please assign me the 'DJ' role and click to make me an MDJM admin.

**Comment by petrknap1** [comment]
Done

**Comment by mikeyhoward1977** [comment]
Am I still a WordPress Administrator?

**Comment by petrknap1** [comment]
No, you are a DJ.

**Comment by mikeyhoward1977** [comment]
Lol... No that's not what I meant :)

Make me an Administrator, then edit my profile and select the following settings...

![untitled-2](https://cloud.githubusercontent.com/assets/11500622/15375176/a4122d0e-1d45-11e6-96f7-5f39418a7042.jpg)

**Comment by petrknap1** [comment]
Aaah, done :-)

**Comment by mikeyhoward1977** [comment]
OK, I got the contract to work for you but its not great news...

For some reason all the existing templates (email and contract) are not allowing you to select them for events.

I fixed the contract by simply copying the content from the original contract and creating a new one. It then allows me to select for events and shows within the Client Zone.

What it means however is that you will likely need to re-create all your email templates :(

A quick way to do this is to install the Post Duplicator plugin. Once you have created the templates again, delete the original ones and make sure your MDJM -> Settings -> Emails & Templates -> Event Templates settings are configured correctly.

Sorry its not better news.

**Comment by petrknap1** [comment]
Thank you Mike, it's not problem.
I'll create new templates.

Where was the problem?

**Comment by mikeyhoward1977** [comment]
To be honest I do not know. I see the existing templates have no author assigned… perhaps it is something to do with that?!?

**Comment by petrknap1** [comment]
Thank you again
