### ISSUE TITLE
Blank page after sign contract

### ISSUE THREAD

**Issue by petrknap1** [mdjmplugin/mobile-dj-manager#58]
Hello,

after sign a contract in client zone appears blank page instead "contract-signed.php". Event is confirmed in MDJM admin but client sees blank page. 
After returning to contract page, second signing is okay.
I tried it on clean installation with same result.

Thank you, Petr

**Comment by mikeyhoward1977** [comment]
How is the contract being accessed for signing? Is the action button being clicked or a direct link/menu item? Can you send me the URL as you land on the page for signing?

**Comment by mikeyhoward1977** [comment]
Can you also confirm your version # and if below 1.3.5 update and try again?

**Comment by petrknap1** [comment]
Hello, I have 1.3.4.1.
The link is direct from client zone.

**Comment by petrknap1** [comment]
I'm going to update it tomorrow.

**Comment by mydjplanner** [comment]
Ok let me know if it is resolved in 1.3.5.x. It should be

On 23 May 2016, at 20:59, petrknap1 notifications@github.com wrote:

I'm going to update it tomorrow.

**Comment by petrknap1** [comment]
I updated to 1.5.5.1 and the same. After refresh the site (F5) is contract signed.

**Comment by mikeyhoward1977** [comment]
What is the URL in the address bar when you have a blank page?

Can you set an event to the awaiting contract status for user jan.drn86 mailto:jan.drn86@seznam.cz……. so I can see?

Thanks
Mike

**Comment by petrknap1** [comment]
Done.
URL is: http://www.kv-production.cz/client-zone-2/event-contract/?event_id=1537

**Comment by mikeyhoward1977** [comment]
Could you enable WordPress debugging as described at http://mdjm.co.uk/docs/debugging-in-mdjm/ http://mdjm.co.uk/docs/debugging-in-mdjm/ ?

I see the issue on your site, but cannot replicate on mine.

Can you also confirm you are using [mdjm-contract] as your page shortcode?

Thanks

**Comment by petrknap1** [comment]
Done.
Debugging manually enabled.

![mdjm_contract](https://cloud.githubusercontent.com/assets/19391308/15488058/9c8c3424-2152-11e6-8603-60f970863b34.jpg)

**Comment by mikeyhoward1977** [comment]
Hi @petrknap1 - Is this resolved?

**Comment by petrknap1** [comment]
Hello Mike,

sorry for my late reply.
Yes, the problem is resolved.

Thank you.
Petr
