### ISSUE TITLE
Transactions in CZK (Czech Koruna)

### ISSUE THREAD

**Issue by petrknap1** [mdjmplugin/mobile-dj-manager#63]
Hello,

I have a problem with transactions in CZK. Total price of event is for example 5000 CZK. If I add new transaction in thousands, for example 1000 CZK as deposit, earning is only 1 CZK and in Client Zone is balance 4 CZK.
Settings of separators is default.

Thank you.
Peter

![transactions](https://cloud.githubusercontent.com/assets/19391308/15603618/0b4d2958-23fc-11e6-8e97-0a11dd6ee519.jpg)

**Comment by mydjplanner** [comment]
Which version #?

On 27 May 2016, at 10:17, petrknap1 notifications@github.com wrote:

Hello,

I have a problem with transactions in CZK. Total price of event is for example 5000 CZK. If I add new transaction in thousands, for example 1000 CZK as deposit, earning is only 1 CZK and in Client Zone is balance 4 CZK.
Settings of separators is default.

Thank you.
Peter

**Comment by petrknap1** [comment]
Last version - yesterdays update.

**Comment by mydjplanner** [comment]
OK, and what method are you using to add the transaction? Are you setting on the event screen under deposit or are you using the add transaction window within the events page?

**Comment by petrknap1** [comment]
I'm using the event screen under deposit.

**Comment by mikeyhoward1977** [comment]
Please send me a screenshot

**Comment by petrknap1** [comment]
The same screen is in my first post.
![transactions](https://cloud.githubusercontent.com/assets/19391308/15626894/af380a12-24d1-11e6-9e19-5fc370553a1a.jpg)

**Comment by mydjplanner** [comment]
Ok it's a formatting issue...resolved for next release. The actual amounts entered are registered correctly

On 28 May 2016, at 11:43, petrknap1 notifications@github.com wrote:

The same screen is in my first post.
