### ISSUE TITLE
balance does not update in client zone

### ISSUE THREAD

**Issue by algarvedjhire** [mdjmplugin/mobile-dj-manager#64]
The Balance in the client Zone does not update when I click Deposit Paid in the admin panel.

**Comment by mikeyhoward1977** [comment]
It is not supposed to. The Balance Paid and Deposit paid checkboxes are an old feature that was used prior to transactions being available. They simply mark the deposit/balance as paid but do not add any transactions. I will remove them shortly.

Until then, add the transactions manually within the event screen
