### ISSUE TITLE
Add shortcode for alternative phone number to emails & calendar sync

### ISSUE THREAD

**Issue by peter8rossi** [mdjmplugin/mobile-dj-manager#76]
With mobile phones and home phones we constantly  manually typing in, or making a note of,  the additional phone number. Could this be added as a short code that does not show if the field is blank?

**Comment by mikeyhoward1977** [comment]
`{client_alt_phone}` will be in the next version

**Comment by peter8rossi** [comment]
Forgot to mention that this is also needed on the calendar.

**Comment by peter8rossi** [comment]
Not sure I should have closed this?
