### ISSUE TITLE
Sort Events (feature request)

### ISSUE THREAD

**Issue by IggyDavis** [mdjmplugin/mobile-dj-manager#86]
default sort. I think the next event should be at the top by default when i click on 'events'. Or, have the ability to save 'my current view' as the default view. (This is because 99% of the time I click events I want to see my next event and I haver to click a few times to get that at the top)

**Comment by rikkilake** [comment]
I too do not like the default sort, I think it makes more sense to sort by creation date, like it did before, so the most recently and relevant quoted events are shown first.

**Comment by mikeyhoward1977** [comment]
It is not possible to sort by next event. If we're sorting by event date, the options we have are ascending or descending... neither of which will guarantee the next event hits the top of the page. The best way to do this is to use the date filters and select the required month - although it is an additional click or two.

As for default sorting, I can certainly add an option so you can select the default sort method between event date, post date (creation), value, type and ID.

I can also add a link from the main WP dashboard within the MDJM Overview widget to the next event
