### ISSUE TITLE
Events - Multiple Columns, (width) extends beyond display area (on mobile)

### ISSUE THREAD

**Issue by rikkilake** [mdjmplugin/mobile-dj-manager#89]
Applies to Custom Fields
Venue Area is now 3 column
- wherever else applicable where >2 columns are in use

Even width of drop-down menus appear to extend the width of the display.

And to make matters worth, pinch and zoom (out) unavailable.

**Comment by mikeyhoward1977** [comment]
Assuming you are referring to a mobile device display...

If I turn my device horizontal (iPhone) everything is displayed correctly

**Comment by rikkilake** [comment]
Emailed screenshots.

**Comment by mikeyhoward1977** [comment]
Per email convo, display is OK when a mobile device is changed to horizontal. Will look to reduce 3 columns to 2 for client/venue details but other rows will remain as is
