### ISSUE TITLE
Events - All Event Types drop down results

### ISSUE THREAD

**Issue by rikkilake** [mdjmplugin/mobile-dj-manager#93]
It's superfluous to the user to repeat the value of the option twice, please remove the brackets.

`<select name="mdjm_filter_type">
<option value="">All Event Types</option>
<option value="42">16th Birthday Party (16th Birthday Party)</option><option value="43">18th Birthday Party (18th Birthday Party)</option><option value="44">21st Birthday Party (21st Birthday Party)</option><option value="45">30th Birthday Party (30th Birthday Party)</option><option value="46">40th Birthday Party (40th Birthday Party)</option><option value="47">50th Birthday Party (50th Birthday Party)</option><option value="48">60th Birthday Party (60th Birthday Party)</option><option value="49">70th Birthday Party (70th Birthday Party)</option><option value="50">Anniversary Party (Anniversary Party)</option><option value="111">Bar / Club (Bar / Club)</option><option value="51">Child Birthday Party (Child Birthday Party)</option><option value="102">Christening (Christening)</option><option value="110">Christmas Party (Christmas Party)</option><option value="52">Corporate Event (Corporate Event)</option><option value="53">Engagement Party (Engagement Party)</option><option value="54">Halloween Party (Halloween Party)</option><option value="55">New Years Eve Party (New Years Eve Party)</option><option value="56">Other (Other)</option><option value="57">School Disco (School Disco)</option><option value="58">School Prom (School Prom)</option><option value="109">Sports Presentation (Sports Presentation)</option><option value="101">Staff Leaving Do (Staff Leaving Do)</option><option value="59">Wedding (Wedding)</option>  </select>`

**Comment by mikeyhoward1977** [comment]
The number of events per category should be displayed within those brackets.

Have addressed for next release;

```
<select name="mdjm_filter_type">
    <option value="">All Event Types</option>
    <option value="130">16th Birthday Party (7)</option>
    <option value="131">18th Birthday Party (2)</option>
    <option value="132">21st Birthday Party (4)</option>
    <option value="133">30th Birthday Party (3)</option>
    <option value="134">40th Birthday Party (27)</option>
    <option value="136">60th Birthday Party (3)</option>
    <option value="139">Child Birthday Party (2)</option>
    <option value="142">Halloween Party (1)</option>
</select>
```

**Comment by rikkilake** [comment]
Great =)
